name: CD - Deploy from CI Artifacts

on:
  workflow_run:
    workflows: ["CI - Build & Publish All Projects"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Local IIS Environment
    runs-on: self-hosted  

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # 1. Confirm Trigger
      - name: Validate CI Completion
        run: |
          Write-Host "CI build completed successfully."
          Write-Host "Starting CD deployment to IIS..."

      # 2. Stop IIS Service
      - name: Stop IIS Service
        shell: pwsh
        run: |
          try {
              Stop-Service -Name 'W3SVC' -Force -ErrorAction Stop
              Write-Host "IIS stopped successfully."
          } catch {
              Write-Host "IIS is not running or already stopped."
          }

      # 3. Clean Old Deployment
      - name: Clean Existing Deployment
        shell: pwsh
        run: |
          $deployPath = "C:\inetpub\wwwroot\NeoSpin"
          if (Test-Path $deployPath) {
              Remove-Item "$deployPath\*" -Recurse -Force -ErrorAction SilentlyContinue
          } else {
              New-Item -ItemType Directory -Path $deployPath | Out-Null
          }

      # 4. Download Artifact from CI Workflow
      - name: Download CI Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "CI - Build & Publish All Projects"
          workflow_conclusion: success
          name: Build-All-Projects
          path: C:\Deployments\NeoSpin

      # 5. Deploy to IIS Folder
      - name: Deploy Application Files
        shell: pwsh
        run: |
          $source = "C:\Deployments\NeoSpin"
          $destination = "C:\inetpub\wwwroot\NeoSpin"
          Copy-Item "$source\*" "$destination" -Recurse -Force -ErrorAction SilentlyContinue
          Write-Host "Deployment completed successfully."

      # 6. Start IIS Service
      - name: Start IIS Service
        shell: pwsh
        run: |
          Start-Service -Name 'W3SVC'
          Write-Host "IIS started successfully."

      # 7. Deployment Summary
      - name: Deployment Summary
        shell: pwsh
        run: |
          Write-Host "---------------------------------------------"
          Write-Host "Deployment Summary"
          Write-Host "Artifacts Source : CI - Build & Publish All Projects"
          Write-Host "Deployed To      : C:\inetpub\wwwroot\NeoSpin"
          Write-Host "Execution Time   : $(Get-Date)"
          Write-Host "---------------------------------------------"
