name: CD - Deploy from CI Artifacts

on:
  workflow_run:
    workflows: ["CI - Build & Publish All Projects"]
    types:
      - completed

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy to Local IIS
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Confirm CI Success
        shell: powershell
        run: |
          Write-Host "CI workflow completed successfully. Starting deployment..."

      - name: Stop IIS Service
        shell: powershell
        run: |
          try {
              Stop-Service -Name 'W3SVC' -Force -ErrorAction Stop
              Write-Host "IIS stopped successfully."
          } catch {
              Write-Host "IIS was not running."
          }

      - name: Clean Deployment Folder
        shell: powershell
        run: |
          $deployPath = "C:\inetpub\wwwroot\NeoSpin"
          if (Test-Path $deployPath) {
              Remove-Item "$deployPath\*" -Recurse -Force -ErrorAction SilentlyContinue
              Write-Host "Cleaned existing deployment directory."
          } else {
              New-Item -ItemType Directory -Path $deployPath | Out-Null
              Write-Host "Created new deployment directory."
          }

      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "CI-Build.yml"   # exact CI file name
          workflow_conclusion: success
          branch: main
          name: Build-All-Projects
          path: C:\Deployments\NeoSpin
          check_artifacts: true

      - name: Deploy to IIS
        shell: powershell
        run: |
          Copy-Item "C:\Deployments\NeoSpin\*" "C:\inetpub\wwwroot\NeoSpin" -Recurse -Force
          Write-Host "Application deployed successfully to IIS."

      - name: Start IIS Service
        shell: powershell
        run: |
          Start-Service -Name 'W3SVC'
          Write-Host "IIS started successfully."

      - name: Deployment Summary
        shell: powershell
        run: |
          Write-Host "---------------------------------------------"
          Write-Host "Deployment Summary"
          Write-Host "Source: CI - Build & Publish All Projects"
          Write-Host "Deployed To: C:\inetpub\wwwroot\NeoSpin"
          Write-Host "Time: $(Get-Date)"
          Write-Host "---------------------------------------------"
