name: CI-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Publish Artifacts
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild slnNeoSpin/slnNeoSpin.sln /p:Configuration=Release
      shell: pwsh

    - name: Prepare Artifact Folder
      shell: pwsh
      run: |
        $output = "${{ runner.temp }}\artifacts"
        if (-not (Test-Path $output)) { New-Item -ItemType Directory -Force -Path $output }
        Write-Host "Artifact directory prepared at: $output"

    - name: Copy All DLLs from All Projects
      shell: pwsh
      run: |
        $staging = "${{ runner.temp }}\artifacts"
        $releaseFolders = Get-ChildItem -Path . -Directory -Recurse | Where-Object { $_.FullName -like '*\bin\Release' }
        foreach ($folder in $releaseFolders) {
            $projectName = Split-Path (Split-Path $folder.FullName -Parent) -Leaf
            $target = Join-Path $staging $projectName
            New-Item -ItemType Directory -Force -Path $target | Out-Null
            Copy-Item "$($folder.FullName)\*" $target -Recurse -Force
            Write-Host " Copied DLLs from project: $projectName"
        }

    - name: Upload All Project DLLs
      uses: actions/upload-artifact@v4
      with:
        name: All-Project-DLLs
        path: ${{ runner.temp }}/artifacts
        if-no-files-found: error
