name: CI-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Publish Artifacts
    runs-on: windows-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 3️⃣ Build the solution
    - name: Build Solution
      run: msbuild slnNeoSpin/slnNeoSpin.sln /p:Configuration=Release
      shell: pwsh

    # 4️⃣ Prepare artifact folder
    - name: Prepare Artifact Folder
      shell: pwsh
      run: |
        $output = "${{ runner.temp }}\artifacts"
        if (-not (Test-Path $output)) { New-Item -ItemType Directory -Force -Path $output }
        Write-Host "Artifact directory prepared at: $output"

    # 5️⃣ Collect all DLLs from Release folders
    - name: Copy DLLs to Artifact Folder
      shell: pwsh
      run: |
        $staging = "${{ runner.temp }}\artifacts"
        Get-ChildItem -Path . -Recurse -Include *.dll | 
          Where-Object { $_.FullName -match 'bin\\Release' } |
          Copy-Item -Destination $staging -Force
        Write-Host "Copied all Release DLLs to $staging"

    # 6️⃣ Upload all as artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-DLLs
        path: ${{ runner.temp }}/artifacts
        if-no-files-found: error
