name: CI-Build-And-Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ---------- BUILD JOB ----------
  build:
    name:  Build All Projects
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore slnNeoSpin/slnNeoSpin.sln

      - name: Build solution (Release mode)
        run: msbuild slnNeoSpin/slnNeoSpin.sln /p:Configuration=Release /m

      # Publish artifacts per project for clarity
      - name: Upload NeoSpinBusinessObjects DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinBusinessObjects
          path: slnNeoSpin/NeoSpinBusinessObjects/bin/Release/**/*.dll

      - name: Upload NeoSpinBatch DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinBatch
          path: slnNeoSpin/NeoSpinBatch/bin/Release/**/*.dll

      - name: Upload NeoSpinBPMEngine DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinBPMEngine
          path: slnNeoSpin/NeoSpinBPMEngine/bin/Release/**/*.dll

      - name: Upload NeoSpinDataAccess DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinDataAccess
          path: slnNeoSpin/NeoSpinDataAccess/bin/Release/**/*.dll

      - name: Upload NeoSpinDBEngine DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinDBEngine
          path: slnNeoSpin/NeoSpinDBEngine/bin/Release/**/*.dll

      - name: Upload NeoSpinScheduler DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinScheduler
          path: slnNeoSpin/NeoSpinScheduler/bin/Release/**/*.dll

      - name: Upload NeoSpinUI DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinUI
          path: slnNeoSpin/NeoSpinUI/bin/Release/**/*.dll

      - name: Upload NeoSpinUtility DLLs
        uses: actions/upload-artifact@v4
        with:
          name: NeoSpinUtility
          path: slnNeoSpin/NeoSpinUtility/bin/Release/**/*.dll

      - name: Upload BPMDeploymentUtility DLLs
        uses: actions/upload-artifact@v4
        with:
          name: BPMDeploymentUtility
          path: slnNeoSpin/BPMDeploymentUtility/bin/Release/**/*.dll


  # ---------- DOWNLOAD JOB ----------
  download:
    name:  Collect All Artifacts
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download All Project DLLs
        uses: actions/download-artifact@v4
        with:
          path: All_Build_DLLs

      - name: Verify downloaded structure
        run: |
          Write-Host "=== Downloaded Artifacts ==="
          Get-ChildItem -Path All_Build_DLLs -Recurse | Select-Object FullName
        shell: pwsh
