name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution silently (logs saved)
      run: |
        msbuild slnNeoSpin/slnNeoSpin.sln /p:Configuration=Release `
        /fl `
        "/flp:logfile=msbuild.log;verbosity=diagnostic" `
        /bl:msbuild.binlog > build_output.txt 2>&1
      shell: pwsh

    - name: Upload logs (always)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: MSBuild-Logs
        path: |
          msbuild.log
          msbuild.binlog
          build_output.txt
